[build]
  framework = "next"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  STORYBLOK_VERSION = "published"

[context.deploy-preview.environment]
  STORYBLOK_VERSION = "draft"

[context.branch-deploy.environment]
  STORYBLOK_VERSION = "draft"

[[plugins]]
  package = "@netlify/plugin-nextjs"
