import './globals.scss';
import StoryblokProvider from '../bloks/StoryblokProvider';
import SvgLogo from '@/bloks/SvgLogo';
import ThemeToggle from '@/components/theme-toggle/theme-toggle';
import { inter } from './fonts';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentYear = new Date().getFullYear();
	return (
		<html lang="sv" className={inter.variable} suppressHydrationWarning>
			<body>
				<StoryblokProvider>
					<header>
						<SvgLogo width={200} height={200} aria-label="Logo" />
						<ThemeToggle />
					</header>
					{children}
					<footer>All rights reserved © {currentYear} </footer>
				</StoryblokProvider>
			</body>
		</html>
	);
}
