import './globals.scss';
import StoryblokProvider from '../bloks/StoryblokProvider';
import SvgLogo from '@/bloks/SvgLogo';
import ThemeToggle from '@/components/theme-toggle/theme-toggle';
import { inter } from './fonts';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="sv" className={inter.variable} suppressHydrationWarning>
			<head>
				{/* Critical resource hints */}
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				{/* Inline critical theme script */}
				<script
					dangerouslySetInnerHTML={{
						__html: `
							try {
								const theme = localStorage.getItem('theme');
								if (theme && theme !== 'system') {
									document.documentElement.setAttribute('data-theme', theme);
								}
							} catch (e) {}
						`,
					}}
				/>
			</head>
			<body>
				<StoryblokProvider>
					<header>
						<SvgLogo width={200} height={200} aria-label="Logo" />
						<ThemeToggle />
					</header>
					{children}
					<footer>All rights reserved © 2026 </footer>
				</StoryblokProvider>
			</body>
		</html>
	);
}
